### PR TITLE
Rebuild for Python 3.7, GCC 7, R 3.5.1, openBLAS 0.3.2

### PR DESCRIPTION
**Pull request by xhochy**
Fixes #6

### CODE REVIEW

**Comment by karalekas** [comment]
closing as is inactive

**Comment by xhochy** [comment]
Without merging this, this package will be unusable on conda-forge.

**Comment by karalekas** [comment]
@xhochy Hey! Could you expand upon your comment? I'm not particularly well versed in conda-forge, and after seeing all these build failures, I decided to figure out a way to get back to `noarch`, which I was able to do successfully in #13. The latest master build worked, and now I am able to `conda install -c conda-forge rpcq==2.5.0` successfully. By "this package" do you mean versions 2.4.0 and 2.4.1? Because I sort of resigned to that reality in going forward with #13, but if there is a way around that I am all ears!

**Comment by xhochy** [comment]
@karalekas Ah, I haven't seen the `noarch` migration. That solves the migration problem that should have been adressed by this PR in a more elegant fashion.

Yes, old versions will not be installable anymore using `conda install -c conda-forge` but only with an old label pre the compiler migration. That is ok as all older packages got that label. 

All in all, we're fine and there is no problem with this package. I just feared that you closed this PR because you were not aware of the compiler migration *and* that master would still be failing. But as the package is now `noarch`, this is no problem. I have seen this in a lot of other cases, so my intuition is nowadays that the rebuild PRs get closed after months while the problem actually still exists.

**Comment by karalekas** [comment]
Great! Thanks so much for the help and feedback!

**Pull request closed without merging**
