### PR TITLE
Fix msgpack-python pin

### PR DESCRIPTION
**Pull request by basnijholt**
See the update here:

https://github.com/rigetti/rpcq/commit/801e7a70c69d17ba26a63b4cef32aa78510c8740

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by basnijholt** [comment]
@conda-forge-admin, please rerender

**Comment by basnijholt** [comment]
@BastianZim @jmackeyrigetti @notmgsk, this will unblock the build for cirq 1.2.0 here https://github.com/conda-forge/cirq-feedstock/pull/13.

Could this please be merged ASAP? 😄

**Comment by BastianZim** [comment]
Feel free to add yourself as a maintainer, if you want.

**Comment by BastianZim** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
